// Electron Forge config. The packaged app is a thin shell that loads
// https://cscd.online (see main.cjs) and includes the local agent runtime.
// The zip maker works everywhere; native installers (.dmg/.exe/.deb/.rpm) are
// gated behind the platform tooling that produces them.
import { execSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { MakerZIP } from '@electron-forge/maker-zip';
import { MakerSquirrel } from '@electron-forge/maker-squirrel';
import { MakerDMG } from '@electron-forge/maker-dmg';
import { MakerDeb } from '@electron-forge/maker-deb';
import { MakerRpm } from '@electron-forge/maker-rpm';

const has = (bin) => {
  try { execSync(`command -v ${bin}`, { stdio: 'ignore' }); return true; }
  catch { return false; }
};
const configDir = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(configDir, '..');

// The Fizzer gem, regenerated by scripts/make-desktop-icons.mjs. Packager wants
// the extensionless path and picks .icns/.ico per platform; the makers each
// want a concrete file, and Linux only reads PNG.
const iconBase = path.resolve(configDir, 'assets', 'icon');
const iconPng = `${iconBase}.png`;

// Always: a runnable zipped app bundle for whichever --platform is requested.
const makers = [new MakerZIP({}, ['darwin', 'linux', 'win32'])];

// Native installers, only where the toolchain exists.
if (process.platform === 'darwin') makers.push(new MakerDMG({ icon: `${iconBase}.icns` }));
if (process.platform === 'win32' || (has('wine') && has('mono'))) {
  makers.push(new MakerSquirrel({ name: 'Fizzer', setupIcon: `${iconBase}.ico` }));
}
if (has('dpkg') && has('fakeroot')) makers.push(new MakerDeb({ options: { name: 'fizzer', productName: 'Fizzer', icon: iconPng } }));
if (has('rpmbuild')) makers.push(new MakerRpm({ options: { name: 'fizzer', productName: 'Fizzer', icon: iconPng } }));

export default {
  packagerConfig: {
    name: 'Fizzer',
    executableName: 'cascade',
    icon: iconBase,
    asar: true,
    // agent-runner.cjs loads the generated local-agent implementation from
    // resources/dist at runtime. Packaging only this Electron directory makes
    // a shell that opens but cannot run or reap agents.
    extraResource: [
      path.join(rootDir, 'dist'),
      path.join(rootDir, 'FIZZER-LICENSE.txt'),
      path.join(rootDir, 'THIRD_PARTY_NOTICES.md'),
      path.join(configDir, 'node_modules', '@resvg', 'resvg-js', 'LICENSE'),
    ],
  },
  makers,
};
